---
title: "Differential abundance analysis"
author: ""
---

```{r setup}
# Source group-assignment
source("../funct.R")

# Load the TreeSummarizedExperiment object
tse <- readRDS("../../data/tse.Rds")
tse <- tse[, tse$paired=="yes"]

taxa_levels <- c("species","genus")

prevalence.th <- 10/100
detection.th <- 0.1/100

variable <- "Diet" 
formula_used <- "~ diet * timepoint + (1 | id)"
correction <- "Benjamini-Hochberg FDR adjustment"

```

Analysis information:

-   Method: maaslin3
-   Taxonomic level: `r taxa_levels`
-   Group variable: `r variable`
-   Formula used: **`r formula_used`**
-   Correction: **`r correction`**
-   Detection threshold: `r 100 * detection.th`%
-   Prevalence threshold: `r 100 * prevalence.th`%

In the report, a suffix of 1~ timepoint 1 and 2~ timepoint 2

```{r tsesub}
file_path1 <- file.path("../../output/daa/daa_taxa/species/all_results.tsv")
file_path2 <- file.path("../../output/daa/daa_taxa/genus/all_results.tsv")

genus_of_interest <- c("Lactobacillus", "Bifidobacterium")
species_of_interest <- c("Bifidobacterium_adolescentis", "Lactobacillus_acidophilus", "Bifidobacterium_animalis", "Lactobacillus_gasseri", "Bifidobacterium_angulatum", "Bifidobacterium_bifidum", "Bifidobacterium_catenulatum", "Lactobacillus_iners", "Bifidobacterium_pullorum", "Tyzzerella_nexilis", "Ruminococcus_gnavus")

taxa_of_interest <- c(genus_of_interest, species_of_interest)

daa_tab1 <- read_tsv(file_path1, col_names = TRUE, show_col_types = FALSE) %>%
      filter(!is.na(feature)) %>%
      filter(model == "abundance") %>%
      filter(feature %in% taxa_of_interest) %>%
      select(feature,metadata, value, qval_joint) 
daa_tab2 <- read_tsv(file_path2, col_names = TRUE, show_col_types = FALSE) %>%
      filter(!is.na(feature)) %>%
      filter(model == "abundance") %>%
      filter(feature %in% taxa_of_interest) %>%
      select(feature,metadata, value, qval_joint)

daa_tab <- rbind(daa_tab1, daa_tab2) %>%
  mutate(qval_joint = signif(qval_joint, digits = 3)) 

```

```{r before-after}
df <- as.data.frame(colData(tse))

plot_taxon <- function(taxon) {
  
  # Check if the taxon exists in genus or species
  if (taxon %in% rowData(tse)$genus | taxon %in% rowData(tse)$species) {
    
    # Calculate signal (relative abundance)
        if (taxon %in% rowData(tse)$genus) {
          rownames(tse) <- rowData(tse)$genus
          df$signal <- as.vector(assay(tse, "relabundance")[taxon,])
        } else {
          rownames(tse) <- rowData(tse)$species
          df$signal <- as.vector(assay(tse, "relabundance")[taxon,])
        }
    
    daa_tab_tax <- daa_tab %>%
      filter(feature == taxon)
    
    anot_tax <- daa_tab_tax %>% 
        filter(metadata == "intervention")
    
    anot_tax$pval_color <- ifelse(anot_tax$qval_joint <= 0.25, "red", "blue")
    # Subset for before and after
    df_before <- df %>% filter(timepoint == "before")
    df_after <- df %>% filter(timepoint == "after")
    
    # Prepare data for plotting
        vars <- c("id", "timepoint", "signal")
        dfm <- melt(df[, vars])
        colnames(dfm) <- vars
        
        # Filter and mutate for paired design
        df <- df %>%
          filter(paired == "yes") %>%
          group_by(id) %>%
          mutate(
            change = if_else(timepoint == "after", signal - signal[timepoint == "before"], 0),
            change = if_else(timepoint == "before", change[timepoint == "after"], change)
          ) %>%
          ungroup() %>%
          as.data.frame(check.names = FALSE)
        
          min_change <- min(df$change, na.rm = TRUE)
          max_change <- max(df$change, na.rm = TRUE)
          median_change <- median(df$change, na.rm = TRUE)
    
    p12 <- ggplot(df, aes(x = diet, y = signal)) +
      geom_boxplot(outlier.shape = NA) +
      geom_point() + 
      scale_y_log10(labels = scales::percent) + 
      theme(text = element_text(size = 25), legend.position = "none") +
      labs(title = taxon, y = "Abundance (%)") +
      facet_wrap(~ timepoint, nrow = 1)
    
    p3 <- ggplot(df, aes(x = timepoint, y = signal)) +
      geom_boxplot(outlier.shape = NA) +
      geom_point() + 
      geom_line(aes(group = id, color = change)) +
      scale_color_gradient2(midpoint = median_change, low = "blue", mid = "white", high = "red", space = "Lab", limits = c(min_change, max_change)) +
      facet_wrap(~ diet) +
      scale_y_log10(labels = scales::percent) + 
      theme(text = element_text(size = 25), legend.position = "right") +
      labs(x = "Time", y = "Abundance (%)")
    
    # Combine the before and after plots
    return(wrap_plots(p12, p3, axes = "collect")
  )
  }
  
  return(NULL)
}
```

```{r}
plots_list <- list()
plots_list <- setNames(lapply(taxa_of_interest, plot_taxon), taxa_of_interest)
```


```{r hits}
#| layout-ncol: 1
#| fig-width: 12 
#| fig-height: 5 

# theme_set(theme_bw(40))
# 
# 
# for (g in unique(tse$meal)) {
# 
#   if (length(rowData(tse))>0) {
#     tseg <- tse[, tse$meal==g] 
#     df <- as.data.frame(colData(tseg)) 
#     
#     for (tax in taxa_of_interest) {
#       # Check if the genus or species exists in the dataset
#       if (tax %in% rowData(tseg)$genus | tax %in% rowData(tseg)$species) {
#         
#         if (tax %in% rowData(tseg)$genus) {
#           rownames(tseg) <- rowData(tseg)$genus
#           df$signal <- as.vector(assay(tseg, "relabundance")[tax,])
#         } else {
#           rownames(tseg) <- rowData(tseg)$species
#           df$signal <- as.vector(assay(tseg, "relabundance")[tax,])
#         }
# 
#         # Prepare data for plotting
#         vars <- c("id", "timepoint", "signal")
#         dfm <- melt(df[, vars])
#         colnames(dfm) <- vars
#         
#         # Filter and mutate for paired design
#         df <- df %>%
#           filter(paired == "yes") %>%
#           group_by(id) %>%
#           mutate(
#             change = if_else(timepoint == "after", signal - signal[timepoint == "before"], 0),
#             change = if_else(timepoint == "before", change[timepoint == "after"], change)
#           ) %>%
#           ungroup() %>%
#           as.data.frame(check.names = FALSE)
#         
#           min_change <- min(df$change, na.rm = TRUE)
#           max_change <- max(df$change, na.rm = TRUE)
#           median_change <- median(df$change, na.rm = TRUE)
#           
#           daa_tab_tax <- daa_tab %>%
#             filter(feature == tax)
#           
#           
#           anot_tax <- daa_tab_tax %>% 
#               filter(value == "x")
#           
#           anot_tax$pval_color <- ifelse(anot_tax$qval_joint <= 0.25, "red", "blue")
# 
#         # Create the plot
#         p <- ggplot(df, aes(x = timepoint, y = signal)) +
#           geom_boxplot(outlier.shape = NA) +
#           geom_point() + 
#           geom_line(aes(group = id, color = change)) +
#           scale_color_gradient2(midpoint = median_change, 
#                                 low = "blue", 
#                                 mid = "white", 
#                                 high = "red", 
#                                 space = "Lab",
#                                 limits = c(min_change, max_change)) +
#           scale_y_log10(labels = scales::percent) + 
#           labs(title = paste(tax, "/", g), y = "Abundance (%)") +
# 
#           theme(
#             plot.title = ggtext::element_markdown() 
#           ) 
#         
#         plots_list[[paste(tax, "0", g, sep = "_")]] <- p
#       }
#     }
#   }
# }
ordered_plots <- plots_list[order(names(plots_list))]
for (plot_name in names(ordered_plots)) {
  print(ordered_plots[[plot_name]])
}
```


```{r table}
file_path <- file.path("../../output/daa/daa_taxa/species/all_results.tsv")
daa_tab <- read_tsv(file_path, col_names = TRUE, show_col_types = FALSE) %>%
      filter(!is.na(feature)) %>%
      select(feature, metadata, value, coef, qval_individual, qval_joint, model)
daa_tab <- daa_tab %>%
  filter(feature %in% species_of_interest)
kable(daa_tab)
```
