---
title: "Differential Abundance Analysis"
format: html
editor: visual
execute:
  echo: true
---

## ANCOM-BCII

```{r setup, include=FALSE}
# #STEP2: PCoA
# Define variables
variable <- "group"  
```

**Group variable: `r variable`**

```{r data-load, message=FALSE, warning=FALSE, echo=FALSE}
# tse <- readRDS("../data/tse.Rds")
source("data.R")
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
#STEP3: ancombc
set.seed(123)
results <- lapply(taxa, function(taxa_level) {
  lapply(comparisons, function(comp) {
    run_ancombc_for_variable(tse, comp, variable, taxa_level)
  })
})
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
datatable(results[[1]][[2]], 
        options = list(pageLength = 10))
datatable(results[[1]][[3]], 
        options = list(pageLength = 10))
datatable(results[[1]][[4]], 
        options = list(pageLength = 10))
datatable(results[[2]][[2]], 
        options = list(pageLength = 10))
datatable(results[[2]][[3]], 
        options = list(pageLength = 10))
datatable(results[[2]][[4]], 
        options = list(pageLength = 10))
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
# #STEP 4: ancombc mix model 
results_mix <- lapply(taxa, function(taxa_level) {
    run_ancombc_mix(tse,taxa_level)
  })
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
results_mix
```
